# Using version 2 as 3 does not support resource constraint options (cpu_*, mem_* limits) for non swarm mode in Compose
version: "2"

services:

    alfresco: 
        build:
          context: ./alfresco
          args:
            ALFRESCO_TAG: ${ALFRESCO_CE_TAG}
            DB: <%=db%>
            API_EXPLORER_TAG: ${API_EXPLORER_TAG}
        mem_limit: <%=ram/2%>m
        environment:
            JAVA_OPTS : '
                -Ddb.username=alfresco
                -Ddb.password=alfresco <% if (db == "postgres") { %>
                -Ddb.driver=org.postgresql.Driver
                -Ddb.url=jdbc:postgresql://postgres:5432/alfresco <% } %> <% if (db == "mariadb") { %>
                -Ddb.driver=com.mysql.cj.jdbc.Driver
                -Ddb.url=jdbc:mysql://mariadb/alfresco?useUnicode=yes\&characterEncoding=UTF-8 <% } %>
                -Dsolr.host=solr6
                -Dsolr.secureComms=none
                -Dsolr.baseUrl=/solr
                -Dindex.subsystem.name=solr6
                -Dalfresco.host=<%=serverName%>
                -Dalfresco.port=<%=port%>
                -Dshare.host=<%=serverName%>
                -Dshare.port=<%=port%>
                -Daos.baseUrlOverwrite=http<% if (https = 'true') { %>s<%}%>://<%=serverName%>/alfresco/aos
                -Ddeployment.method=DOCKER_COMPOSE
                -Dcsrf.filter.enabled=false <% if (ftp == 'true') { %>
                -Dftp.enabled=true
                -Dftp.port=2121
                -Dftp.dataPortFrom=2433
                -Dftp.dataPortTo=2434 <% } %>
                -Dalfresco.restApi.basicAuthScheme=true
                -Dmessaging.subsystem.autoStart=false
                -Dauthentication.protection.enabled=false
                -XX:+UseG1GC -XX:+UseStringDeduplication
                -Xms<%=(ram/2) - 512%>m -Xmx<%=(ram/2) - 512%>m <% if (smtp == 'true') { %>
                -Dmail.host=smtp
                -Dmail.port=25 
                -Dmail.username=anonymous 
                -Dmail.password=
                -Dmail.protocol=smtp 
                -Dmail.smtps.starttls.enable=false 
                -Dmail.smtps.auth=false <% } %> <% if (ldap == 'true') { %>
                -Dauthentication.chain=alfinst:alfrescoNtlm,ldap1:ldap
                -Dldap.authentication.active=true
                -Dldap.authentication.java.naming.provider.url=ldap://openldap:389
                -Dldap.authentication.userNameFormat=uid=%s,dc=keensoft,dc=es
                -Dldap.synchronization.active=false <% } %> <% if (ocr == 'true') { %>
                -Docr.command=/opt/alfresco/bin/ocrmypdf.sh 
                -Docr.output.verbose=true
                -Docr.output.file.prefix.command=
                -Docr.extra.commands="-j1 --author keensoft --rotate-pages -l spa+eng+fra --deskew --clean --skip-text"
                -Docr.server.os=linux <% } %>
                '
        volumes:
            - ./data/alf-repo-data:/usr/local/tomcat/alf_data
            - ./logs/alfresco:/usr/local/tomcat/logs <% if (ocr == 'true') { %>
            - ./data/ocr/input:/ocr_input
            - ./data/ocr/output:/ocr_output <% } %>
        <% if (ftp == 'true') { %>
        ports:
            - 2121:2121
            - 2433:2433
            - 2434:2434 <% } %>
    
    solr6:
        build:
          context: ./search
          args:
            SEARCH_TAG: $SEARCH_CE_TAG
            SOLR_HOSTNAME: solr6
            ALFRESCO_HOSTNAME: alfresco 
            ALFRESCO_COMMS: none
            CROSS_LOCALE: "<%=crossLocale%>"
        mem_limit: <%=ram/4%>m
        environment:
            #Solr needs to know how to register itself with Alfresco
            SOLR_ALFRESCO_HOST: "alfresco"
            SOLR_ALFRESCO_PORT: "8080"
            #Alfresco needs to know how to call solr
            SOLR_SOLR_HOST: "solr6"
            SOLR_SOLR_PORT: "8983"
            #Create the default alfresco and archive cores
            SOLR_CREATE_ALFRESCO_DEFAULTS: "alfresco,archive"
            SOLR_JAVA_MEM: "-Xms<%=(ram/4) - 256%>m -Xmx<%=(ram/4) - 256%>m"
            SOLR_OPTS: "
                -XX:NewSize=<%=(ram/8) - 256%>m
                -XX:MaxNewSize=<%=(ram/8) - 256%>m
            "
        volumes:
            - ./data/solr-data:/opt/alfresco-search-services/data

    share:
        build:
          context: ./share
          args:
            SHARE_TAG: ${SHARE_TAG}
        mem_limit: <%=ram/8%>m
        environment:
            REPO_HOST: "alfresco"
            REPO_PORT: "8080"
            JAVA_OPTS: "
                -Xms<%=(ram/8) - 128%>m -Xmx<%=(ram/8) - 128%>m
                -Dalfresco.context=alfresco
                -Dalfresco.protocol=http
                "
        volumes:
            - ./logs/share:/usr/local/tomcat/logs

    <% if (db == 'postgres') { %>    
    postgres:
        image: postgres:${POSTGRES_TAG}
        mem_limit: <%=ram/8%>m
        environment:
            - POSTGRES_PASSWORD=alfresco
            - POSTGRES_USER=alfresco
            - POSTGRES_DB=alfresco
        command: "
            postgres
              -c max_connections=200
              -c logging_collector=on
              -c log_min_messages=LOG
              -c log_directory=/var/log/postgresql"
        ports:
            - 5432:5432
        volumes:
            - ./data/postgres-data:/var/lib/postgresql/data
            - ./logs/postgres:/var/log/postgresql
    <% } %> <% if (db == 'mariadb') { %>    
    mariadb:
        image: mariadb:latest
        mem_limit: <%=ram/8%>m
        environment:
            - MYSQL_ROOT_PASSWORD=alfresco
            - MYSQL_DATABASE=alfresco
            - MYSQL_USER=alfresco
            - MYSQL_PASSWORD=alfresco
        command: "mysqld
            --character-set-server=utf8
            --collation-server=utf8_bin
            --lower_case_table_names=1
            --max_connections=200
            --innodb-flush-method=O_DIRECT
            --wait_timeout=28800"
        volumes:
            - ./data/mariadb_data:/var/lib/mysql
            - ./logs/mariadb:/var/log/mysql
        ports:
            - 3306:3306
    <% } %>

    content-app:
        image: alfresco/alfresco-content-app:${ACA_TAG}
        mem_limit: 256m
        depends_on:
            - alfresco

    # HTTP proxy to provide HTTP Default port access to services
    # SOLR API and SOLR Web Console are protected to avoid unauthenticated access
    proxy:
        image: nginx:stable-alpine
        mem_limit: 128m
        depends_on:
            - alfresco
            - solr6
            - share
            - content-app
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf
            - ./config/nginx.htpasswd:/etc/nginx/conf.d/nginx.htpasswd <% if (https = 'true') { %>
            - ./config/cert/localhost.cer:/etc/nginx/localhost.cer
            - ./config/cert/localhost.key:/etc/nginx/localhost.key <% } %>
        ports:
            - <%=port%>:<%=port%>    

    <% if (smtp == 'true') { %>    
    smtp:
        image: mwader/postfix-relay
        mem_limit: 128m
    <% } %>

    <% if (ldap == 'true') { %>
    openldap:
        image: osixia/openldap
        mem_limit: 128m
        container_name: openldap
        environment:
          LDAP_DOMAIN: "alfresco.org"
          LDAP_BASE_DN: "dc=alfresco,dc=org"
          LDAP_ADMIN_PASSWORD: "admin"
        volumes: 
            - ./data/ldap:/var/lib/ldap
            - ./data/slap.d:/etc/ldap/slap.d

    phpldapadmin:
        image: osixia/phpldapadmin
        mem_limit: 128m
        container_name: phpldapadmin
        environment:
          PHPLDAPADMIN_LDAP_HOSTS: "openldap"
          PHPLDAPADMIN_HTTPS=false:
        links:
            - openldap
        depends_on:
            - openldap
        ports:
            - 8088:80
    <% } %>

    <% if (ocr == 'true') { %>
    ocrmypdf:
        build: ./ocrmypdf
        mem_limit: 512m
        hostname: ocrmypdf
        volumes:
            - ./data/ocr/input:/ocr_input
            - ./data/ocr/output:/ocr_output
    <% } %>